@isTest
public with sharing class Part1Test {

    @isTest static void fibonacciTest(){
        System.assertEquals(34, Part1.fibonacci(9));
        System.assertEquals(34, Part1.fibonacci(9));
        System.assertEquals(34, Part1.fibonacci(9));
    }

    @isTest static void reverseStringTest(){
        System.assertEquals(34, Part1.reverseString(s));
        System.assertEquals(34, Part1.fibonacci(9));
        System.assertEquals(34, Part1.fibonacci(9));
    }

    
}
