/**
 * Created by gamedevmadeeasy on 10/13/19.
 */

public with sharing class StudentRemoval {
    // A Student who has three unexcused absences from three different classes
    // should be suspended and unable to enroll in another class during that time.
    //    - If this happens for a fourth class, they should be expelled.
    public Integer getStudentUnexcusedAbsentCount(Student__c Id) {

    }

    public Student__c suspendStudent(Student__c Id) {

    }

    public Student__c expelStudent(Student__c Id) {

    }
}