public with sharing class UserPermissionErrors {
    public static final String CANNOT_READ_ASSESSMENTS = 'You do not have access to see Assessment records. Please contact System Administrator for more details.';
    public static final String CANNOT_CREATE_ASSESSMENTS = 'You do not have permission to create Assessments. Please contact System Administrator if this is unexpected.';
    public static final String CANNOT_READ_CLASSES = 'You do not have access to see Class records. Please contact System Administrator for more details.';
    public static final String CANNOT_CREATE_CLASSENROLLMENT = 'You do not have access to see Class Enrollment records. Please contact System Administrator for more details.';
    public static final String CANNOT_CREATE_ATTENDANCE_LINE_ITEMS = 'You  cannot create Attendance line items. Please contact System Administrator for more details.';
    public static final String CANNOT_DELETE_ATTENDANCE_LINE_ITEMS = 'Ypu cannot delete Attendance Line items. Please contact System Administrator for more details.';
}